baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'WinUtil Docs'
theme = 'lotusdocs'
enableGitInfo = true

[params]
  themeVariant = ['relearn-dark','relearn-light' ]
  linkTitle = 'Relearn'
  collapsibleMenu = true
  disableLandingPageButton = true
  editURL = 'https://github.com/Chris-Titus-Docs/winutil-docs/edit/main/content/${FilePath}'

[module]
  [[module.mounts]]
    source = 'README.md'
    target = 'assets/README.md'
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false